version: '3.8'

services:

  database:
    image: mysql:latest
    container_name: data-bank
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_bank
      MYSQL_USER: data_user
      MYSQL_PASSWORD: 1106
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - data_network_bank

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MySQLphpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - data_network_bank

volumes:
  db_data:

networks:
  data_network_bank:
    driver: bridge
