version: '3.8'

services:

  database:
    image: postgres:latest
    container_name: data_bank_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1106
      POSTGRES_DB: data_bank
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - data_bank_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: data_bank_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1106
    ports:
      - "8080:80"
    networks:
      - data_bank_network

volumes:
  db_data:

networks:
  data_bank_network:
    driver: bridge
